'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { useAuth } from '@/context/AuthContext'
import { useLocale } from '@/context/LocaleContext'
import { resolveErrorMessage, getValidationErrors } from '@/lib/errors'

export default function RegisterPage() {
  const { register } = useAuth()
  const { t, locale } = useLocale()
  const router = useRouter()

  const [form, setForm] = useState({
    name: '', email: '', password: '', password_confirmation: ''
  })
  const [fieldErrors, setFieldErrors] = useState<Record<string, string[]>>({})
  const [generalError, setGeneralError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) =>
    setForm(prev => ({ ...prev, [e.target.name]: e.target.value }))

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setFieldErrors({})
    setGeneralError(null)
    setLoading(true)
    try {
      await register(form.name, form.email, form.password, form.password_confirmation)
      router.push('/products')
    } catch (err) {
      // Validation field errors are safe to display (generated by FormRequest rules)
      const validationErrors = getValidationErrors(err)
      if (validationErrors) {
        setFieldErrors(validationErrors)
        setGeneralError(resolveErrorMessage(err, locale))
      } else {
        setGeneralError(resolveErrorMessage(err, locale))
      }
    } finally {
      setLoading(false)
    }
  }

  const fieldLabel: Record<string, string> = {
    name: t('register.name'),
    email: t('register.email'),
    password: t('register.password'),
    password_confirmation: t('register.confirmPassword'),
  }

  return (
    <div className="auth-page">
      <div className="auth-card">
        <h2>{t('register.title')}</h2>
        {generalError && <div className="alert alert-error">{generalError}</div>}
        <form onSubmit={handleSubmit}>
          {(['name', 'email', 'password', 'password_confirmation'] as const).map((field) => (
            <div className="form-group" key={field}>
              <label htmlFor={field}>{fieldLabel[field]}</label>
              <input id={field} name={field}
                type={field.includes('password') ? 'password' : field === 'email' ? 'email' : 'text'}
                value={form[field]} onChange={handleChange} required />
              {fieldErrors[field] && (
                <p className="error-msg">{fieldErrors[field][0]}</p>
              )}
            </div>
          ))}
          <button type="submit" disabled={loading} className="btn btn-primary"
            style={{ width: '100%', marginTop: '0.5rem' }}>
            {loading ? t('register.loading') : t('register.submit')}
          </button>
        </form>
        <p style={{ textAlign: 'center', marginTop: '1.5rem', color: '#666' }}>
          {t('register.hasAccount')}{' '}
          <Link href="/login" style={{ color: '#1a1a2e', fontWeight: 600 }}>
            {t('register.loginLink')}
          </Link>
        </p>
      </div>
    </div>
  )
}
