/**
 * Error normalizer for API responses.
 *
 * The backend returns structured errors: { error: 'ERROR_CODE', message: '...' }
 * This module maps those codes to safe, translated UI messages.
 *
 * Design principles:
 * - Never show raw backend messages directly to the user in production UI.
 * - Map machine-readable error codes to translated strings.
 * - For unknown errors, always show a generic safe message.
 * - Validation field errors ARE shown (they are safe by design — generated by FormRequest rules).
 */

import type { Locale } from '@/context/LocaleContext'

/** Structured error from the API */
export interface ApiError {
  error?: string
  message?: string
  errors?: Record<string, string[]>  // validation field errors
  status?: number
}

/** Maps backend error codes to translation keys */
const ERROR_CODE_MAP: Record<string, string> = {
  VALIDATION_ERROR:      'errors.validation',
  UNAUTHENTICATED:       'errors.unauthenticated',
  FORBIDDEN:             'errors.forbidden',
  NOT_FOUND:             'errors.notFound',
  TOO_MANY_REQUESTS:     'errors.tooManyRequests',
  METHOD_NOT_ALLOWED:    'errors.methodNotAllowed',
  SERVICE_UNAVAILABLE:   'errors.serviceUnavailable',
  SERVER_ERROR:          'errors.server',
  // Passport / OAuth codes
  invalid_client:        'errors.invalidCredentials',
  invalid_grant:         'errors.invalidCredentials',
  unsupported_grant_type:'errors.server',
}

const MESSAGES: Record<Locale, Record<string, string>> = {
  en: {
    'errors.validation':       'Please check the form and correct any errors.',
    'errors.unauthenticated':  'Please sign in to continue.',
    'errors.forbidden':        'You do not have permission to do that.',
    'errors.notFound':         'The requested item was not found.',
    'errors.tooManyRequests':  'Too many attempts. Please wait a moment.',
    'errors.methodNotAllowed': 'This action is not allowed.',
    'errors.serviceUnavailable': 'The service is temporarily unavailable.',
    'errors.server':           'An unexpected error occurred. Please try again.',
    'errors.invalidCredentials': 'Invalid email or password.',
    'errors.network':          'Network error. Check your connection and try again.',
    'errors.unknown':          'Something went wrong. Please try again.',
  },
  es: {
    'errors.validation':       'Por favor revisa el formulario y corrige los errores.',
    'errors.unauthenticated':  'Por favor inicia sesión para continuar.',
    'errors.forbidden':        'No tienes permiso para realizar esta acción.',
    'errors.notFound':         'El recurso solicitado no fue encontrado.',
    'errors.tooManyRequests':  'Demasiados intentos. Por favor espera un momento.',
    'errors.methodNotAllowed': 'Esta acción no está permitida.',
    'errors.serviceUnavailable': 'El servicio no está disponible temporalmente.',
    'errors.server':           'Ocurrió un error inesperado. Por favor intenta de nuevo.',
    'errors.invalidCredentials': 'Correo electrónico o contraseña incorrectos.',
    'errors.network':          'Error de red. Verifica tu conexión e intenta de nuevo.',
    'errors.unknown':          'Algo salió mal. Por favor intenta de nuevo.',
  },
}

/**
 * Resolves a safe, translated error message from an API error response.
 *
 * @param err  - Raw error (ApiError object, Error, or unknown)
 * @param locale - Current UI locale
 * @returns    - Safe user-facing message string
 */
export function resolveErrorMessage(err: unknown, locale: Locale = 'en'): string {
  const msgs = MESSAGES[locale]

  // Network failure (fetch threw before getting a response)
  if (err instanceof TypeError && err.message.includes('fetch')) {
    return msgs['errors.network']
  }

  const apiErr = err as ApiError

  // Map by error code first (most specific)
  if (apiErr?.error && ERROR_CODE_MAP[apiErr.error]) {
    return msgs[ERROR_CODE_MAP[apiErr.error]]
  }

  // Map by HTTP status
  if (apiErr?.status) {
    if (apiErr.status === 401) return msgs['errors.unauthenticated']
    if (apiErr.status === 403) return msgs['errors.forbidden']
    if (apiErr.status === 404) return msgs['errors.notFound']
    if (apiErr.status === 429) return msgs['errors.tooManyRequests']
    if (apiErr.status >= 500)  return msgs['errors.server']
  }

  return msgs['errors.unknown']
}

/**
 * Returns field-level validation errors (safe to display — generated by FormRequest).
 * Returns null if the error is not a validation error.
 */
export function getValidationErrors(err: unknown): Record<string, string[]> | null {
  const apiErr = err as ApiError
  if (apiErr?.error === 'VALIDATION_ERROR' && apiErr.errors) {
    return apiErr.errors
  }
  return null
}
